server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://59.110.227.223:3307/integralTest?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 188389han
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    # redis数据库索引(默认为0)，我们使用索引为3的数据库，避免和其他数据库冲突
    database: 3
    # redis服务器地址（默认为loaclhost）
    host: 59.110.227.223
    # redis端口（默认为6379）
    port: 6379
    # redis访问密码（默认为空）
    password: 188389han
    # redis连接超时时间（单位毫秒）
    timeout: 0
    # redis连接池配置
    pool:
      # 最大可用连接数（默认为8，负数表示无限）
      max-active: 8
      # 最大空闲连接数（默认为8，负数表示无限）
      max-idle: 8
      # 最小空闲连接数（默认为0，该值只有为正数才有用）
      min-idle: 0
      # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
      max-wait: -1

mybatis:
  # 配置mapper.xml文件所在的路径
  mapper-locations: classpath*:mapper/*.xml
  # 配置映射类所在的包名
  type-aliases-package: com.zjrc.sm2.dao
  # 数据库字段名下换线转为小驼峰命名
  configuration:
    map-underscore-to-camel-case: true


